theme: jekyll-theme-minimal
title: Advanced Topics in Digital Korean Studies: International Symposia & Project Incubation Program
description: Description Appears Here
url: https://digitalkoreanstudies.github.io/
author:
 name   : "Javier Cha"
 bio    : "Associate Professor of East Asian Studies, College of Liberal Studies, Seoul National University"
