theme: jekyll-theme-slate
title: "Advanced Topics in Digital Korean Studies: International Symposia & Project Incubation Program"
name: "Name"
description: Description Appears Here
url: https://digitalkoreanstudies.github.io/
author:
 name   : "Javier Cha"
 bio    : "Associate Professor of East Asian Studies, College of Liberal Studies, Seoul National University"

footer:
 links:
  - label: "Hi"
